version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Première étape
          command: |
            echo 'Bonjour'
            echo 'Je suis un pipeline'
      - run:
          name: Le code est arrivé
          command: |
            ls -al
            echo '^^^Fin du programme^^^'
